name: NCuboid
version: 0.0.0
description: Cuboid node of the N plugins suite
author: Ribesg
website: http://itsn3w.fr/
main: com.github.ribesg.ncuboid.NCuboid
load: STARTUP

commands:
    cuboid:
        description: General cuboid command
        aliases: [c,cubo]
        permission: ncuboid.cmd.general
        usage: |
            §c/<command> help